### ISSUE TITLE
Is there a document to implement advanced options onEnded and PageSizeOptions

### ISSUE THREAD

**Issue by sujaydinakar** [mudigal-technologies/ngx-audio-player#102]
ERROR in src/app/modules/components/ngx-audio-prayer/ngx-audio-prayer.component.html(2,60): Property 'pageSizeOptions' does not exist on type 'NgxAudioPrayerComponent'.
src/app/modules/components/ngx-audio-prayer/ngx-audio-prayer.component.html(2,96): Property 'onEnded' does not exist on type 'NgxAudioPrayerComponent'.

ERROR in src/app/modules/components/ngx-audio-prayer/ngx-audio-prayer.component.html(2,60): Property 'pageSizeOptions' does not exist on type 'NgxAudioPrayerComponent'.

**Comment by vmudigal** [comment]
There is a typo in the components name "NgxAudioPrayerComponent" and "ngx-audio-prayer/ngx-audio-prayer.component.html".  Could that be an issue? Closing it for now.
