### ISSUE TITLE
Streaming audio urls

### ISSUE THREAD

**Issue by jwhijazi** [mudigal-technologies/ngx-audio-player#15]
Thanks for developing this component.

I'm using your ngx-audio-player for streaming audio from url.
The player is working fine but the end time displayed looks like this (-ty:aN).
I think this is because the stream doesn't contain end time.

So it would be great if you consider the situation when the stream url is endless.

Thanks.

**Comment by jossemarGT** [comment]
Hey @jwhijazi  I think you are looking for `displayDuration` property. Happy hacking :octocat:

**Comment by vmudigal** [comment]
Fixed in v12.0.1
