### ISSUE TITLE
require play, pause and stop events

### ISSUE THREAD

**Issue by mohitande** [mudigal-technologies/ngx-audio-player#40]

**Comment by vmudigal** [comment]
Could you please explain in detail? Play and pause are already there right? And why stop when you could just pause?

**Comment by karincayazilim** [comment]
I need the on Start () button to start it. I wonder if you can. Slider (for rewind) disable feature required.

**Comment by karincayazilim** [comment]
We can understand that it has stopped but you do not return any information that it has started. I want to disable items on my page when it starts playing

**Comment by karincayazilim** [comment]
Can we turn off the STOP feature. Can he steal once to the end? you can't stop

**Comment by karincayazilim** [comment]
any solution please.. @vmudigal

**Comment by vmudigal** [comment]
@karincayazilim, I will work on this. :)

**Comment by karincayazilim** [comment]
not working in IOS thanks you

**Comment by OleksandrGryb** [comment]
Hello, I need to stop track when user click on button but not at player button, how can I do it?

**Comment by vmudigal** [comment]
Fixed in v12.0.1
