### ISSUE TITLE
track ended event returns only an "ended" string

### ISSUE THREAD

**Issue by anshup7** [mudigal-technologies/ngx-audio-player#99]
It should send the reference to current sound controls object so that the sound can be stopped. In default settings the sound continues to play

**Comment by VasuInukollu** [comment]
You can try to remove the playlist when you receive the event. It is a work around and not a solution.

**Comment by LucaDaniele99** [comment]
Had the same issue, the workaround is to save the track array in a local variable when the function is called, set the the player track array loaded in the player to empty array and then load the local variable in the player track array.

Example:
let track_array = [...this.audioguide['track']];
this.audioguide['track'] = [];
this.audioguide['track'] = [...track_array];

**Comment by vmudigal** [comment]
Fixed in v12.0.1
